<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $view \Dotdigitalgroup\Sms\ViewModel\TelephoneInputConfig
 */
// @codingStandardsIgnoreFile
$view = $block->getData('config');
?>
<script type="application/javascript">
    require([
        'jquery',
        'Dotdigitalgroup_Sms/js/intlTelInput'
    ], function ($, intlTelInput) {
        ddgTelephoneRenderComplete = function(node) {
            let telephoneInput = $(node)[0],
                iti = window.intlTelInput(telephoneInput, <?= $view->getConfig(); ?>);

            telephoneInput.addEventListener('blur', function() {
                telephoneInput.value = iti.getNumber();
                telephoneInput.dispatchEvent(new Event('change'));
            });

            document.addEventListener('numberIsInvalid', function(event) {
                telephoneInput.value = event.detail.number;
                telephoneInput.value = iti.getNumber();
                telephoneInput.dispatchEvent(new Event('change'));
            });
        }
    });
</script>
