<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $view \Dotdigitalgroup\Sms\ViewModel\TelephoneInputConfig
 */
// @codingStandardsIgnoreFile
$view = $block->getData('config');
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Dotdigitalgroup_Sms/js/internationalTelephoneInputCheckout": <?= $view->getConfig(); ?>
    },

    ".form-address-edit": {
        "validation": {
            "rules": {
                "telephone": {
                    "validate-phone-number":true
                }
            }
        }
    }
}
</script>

