<script>
    (() => {
        const consentCheckbox = document.getElementById('dd_sms_marketing_consent_checkbox');
        const telephoneElements = document.querySelectorAll('.dd-telephone');
        const consentText = document.getElementById('dd_sms_marketing_consent_text');

        Array.from(telephoneElements).forEach(function(element) {
            element.style.display = 'none';
        });

        consentText.style.display = 'none';

        consentCheckbox.addEventListener('change', function() {
            Array.from(telephoneElements).forEach(function(element) {
                element.style.display = element.style.display === 'none' ? '' : 'none';
            });

            consentText.style.display = consentText.style.display === 'none' ? '' : 'none';
        });
    })();
</script>
