<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper \Magento\Framework\Escaper
 * @var $view \Dotdigitalgroup\Sms\ViewModel\Customer\Account\MarketingConsent
 */
// phpcs:disable Magento2.Legacy.EscapeMethodsOnBlockClass
// @codingStandardsIgnoreFile
$view = $block->getData('config');
?>

<fieldset class="fieldset">
    <?php if ($block->getData('printLegend')): ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('SMS Marketing Subscription')) ?></span></legend>
    <?php endif; ?>
    <div class="field choice">
        <input type="checkbox" name="is_sms_subscribed" id="dd_sms_consent_checkbox" value="1" title="SMS Marketing Subscription"
            <?php if ($view->isSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
        <label for="dd_sms_consent_checkbox" class="label">
            <span><?= $block->escapeHtml($view->getSmsSignUpText()) ?></span>
        </label>
    </div>
    <div class="field telephone dd-telephone">
        <input type="text"
               name="mobile_number"
               id="dd_sms_consent_mobile_number"
               class="input-text"
               value="<?= $block->escapeHtml($view->getStoredMobileNumber()) ?>"
               data-validate='{"validate-phone-number-with-checkbox": <?= $view->isPhoneNumberValidationEnabled(); ?>}'
        />
    </div>
    <div id="dd_sms_consent_text" class="dd-sms-consent-text">
        <p><span><?= $block->escapeHtml($view->getSmsMarketingConsentText()); ?></span><p>
    </div>
</fieldset>
